#! /usr/bin/perl

# Run FindBugs on some standard test files.
# We compare summaries of the output against known good results
# to ensure that we're not producing drastically different results.

use strict qw(refs vars);

my @jarList = (
	'test/dumb.jar', # our test cases
	'/export/home/daveho/linux/java/j2sdk1.4.2/jre/lib/rt.jar', # JDK 1.4.2-beta rt.jar file (build 1.4.2-beta-b19)
	'/export/home/daveho/t/classpath.jar', # Classpath 0.05
);

my $JVM_ARGS = '-Xmx256m';

print "FindBugs regression testing...\n";

foreach my $jar (@jarList) {
	$jar =~ m,.*/([^/]+)\.jar$,;
	my $shortName = $1;

	print "Executing regression test for $shortName\n";

	my $outFile = "build/$shortName.out";

	my $rc = system("bin/findbugs -textui -jvmArgs '$JVM_ARGS' $jar | etc/summarizeBugs > $outFile");
	if ($rc/256 != 0) {
		print STDERR "Command failed!\n";
		exit 1;
	}

	my $oracleFile = "etc/$shortName.oracle";
	if (-r "$oracleFile") {
		print "Bug deltas against last version:\n";
		system("etc/diffBugSummaries $oracleFile $outFile");
	} else {
		print "No oracle exists for test case $shortName\n";
	}
}

# vim:ts=4
