#! /usr/bin/perl

use strict qw(refs vars);

my %counts = ();

while (<>) {
	if (/^(\S+\s+)?(\S+):/) {
		$counts{$2}++;
	}
}

foreach my $key (sort keys %counts) {
	my $count = $counts{$key};
	print "$key:\t$count\n";
}
