/*
 * AboutDialog.java
 *
 * Created on April 6, 2003, 7:05 PM
 */

package edu.umd.cs.findbugs.gui;

import javax.swing.ImageIcon;

/**
 * The Help:About dialog.
 * @author David Hovemeyer
 */
public class AboutDialog extends javax.swing.JDialog {
    
    private FindBugsFrame parent;
    private java.net.URL aboutURL;
    private java.net.URL licenseURL;
    
    /** Creates new form AboutDialog */
    public AboutDialog(FindBugsFrame parent, boolean modal) {
	super(parent, modal);
        this.parent = parent;
        aboutURL = getClass().getClassLoader().getResource("edu/umd/cs/findbugs/gui/help/About.html");
        licenseURL = getClass().getClassLoader().getResource("edu/umd/cs/findbugs/gui/help/License.html");
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        aboutTabPane = new javax.swing.JTabbedPane();
        aboutScrollPane = new javax.swing.JScrollPane();
        aboutEditorPane = new javax.swing.JEditorPane();
        licenseScrollPane = new javax.swing.JScrollPane();
        licenseEditorPane = new javax.swing.JEditorPane();
        jSeparator1 = new javax.swing.JSeparator();
        okButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("About FindBugs");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        try {
            aboutEditorPane.setPage(aboutURL);
        } catch (java.io.IOException e) {
            parent.getLogger().logMessage(ConsoleLogger.ERROR, "Error loading about URL: " + e.getMessage());
        }
        aboutScrollPane.setViewportView(aboutEditorPane);

        aboutTabPane.addTab("About", aboutScrollPane);

        try {
            licenseEditorPane.setPage(licenseURL);
        } catch (java.io.IOException e) {
            parent.getLogger().logMessage(ConsoleLogger.ERROR, "Error loading license URL: " + e.getMessage());
        }
        licenseScrollPane.setViewportView(licenseEditorPane);

        aboutTabPane.addTab("License", licenseScrollPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(aboutTabPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jSeparator1, gridBagConstraints);

        okButton.setMnemonic('O');
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        getContentPane().add(okButton, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        closeDialog();
    }//GEN-LAST:event_okButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
	closeDialog();
    }//GEN-LAST:event_closeDialog
    
    private void closeDialog() {
	setVisible(false);
	dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane licenseScrollPane;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane aboutScrollPane;
    private javax.swing.JEditorPane licenseEditorPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JEditorPane aboutEditorPane;
    private javax.swing.JTabbedPane aboutTabPane;
    // End of variables declaration//GEN-END:variables
    
}
