#! /bin/sh

@GET_FBHOME@

@SET_DEFAULT_JAVA@

out='no'
fb_jvmargs=''
 
while [ $# -gt 0 ] && [ "$out" = "no" ]; do
	case $1 in
	-bycode)
		shift
		fb_jvmargs="-Dfindbugs.categorize.byCodeOnly=true $fb_jvmargs"
		;;
 
	*)
		out='yes'
		;;
	esac
done

fb_mainclass=edu.umd.cs.findbugs.workflow.CategorizeBugs

@WRAP_JAVA@

# vim:ts=3
