#! /bin/sh

# Launch FindBugs from the command line.

@GET_FBHOME@

@SET_DEFAULT_JAVA@

maxheap=256

Usage() {
	echo "Usage: findbugs [options]"
	echo "   -gui            Use the Graphical UI (default behavior)"
	echo "   -textui         Use the Text UI"
	echo "   -jvmArgs args   Pass args to JVM"
	echo "   -maxHeap size   Maximum Java heap size in megabytes (default=$maxheap)"
	echo "   -javahome dir   Specify location of JRE"
	echo "   -help           Display this message"
	echo "   -debug          Enable debug tracing in FindBugs"
	echo "   -conserveSpace  Conserve memory at the expense of precision"
	echo "All other options are passed to the FindBugs application"
	exit 0
}

# Set defaults
fb_appjar="$findbugs_home/lib/findbugsGUI.jar"
user_jvmargs=''
debug_arg=''
conservespace_arg=''
user_props=''

# Handle command line arguments.
out='no'
while [ $# -gt 0 ] && [ "$out" = "no" ]; do
	case $1 in
	-gui)
		shift
		fb_appjar="$findbugs_home/lib/findbugsGUI.jar"
		;;

	-textui)
		shift
		fb_appjar="$findbugs_home/lib/findbugs.jar"
		;;

	-jvmArgs)
		shift
		user_jvmargs="$1"
		shift
		;;

	-maxHeap)
		shift
		maxheap="$1"
		shift
		;;

	-javahome)
		shift
		fb_javacmd="$1/bin/java"
		shift
		;;

	-debug)
		shift
		debug_arg="-Dfindbugs.debug=true"
		;;

	-conserveSpace)
		shift
		conservespace_arg="-Dfindbugs.conserveSpace=true"
		;;

	-property)
		shift
		user_props="-D$1 $user_props"
		shift
		;;

	-help)
		Usage
		;;

	*)
		out='yes'
		;;
	esac
done

fb_jvmargs="$user_jvmargs $debug_arg $conservespace_arg $user_props"
fb_maxheap="-Xmx${maxheap}m"

# Extra JVM args for MacOSX.
if [ $fb_osname = "Darwin" ]; then
	fb_jvmargs="$fb_jvmargs \
		-Xdock:name=FindBugs -Xdock:icon=${findbugs_home}/lib/bug-logo.icns \
		-Dapple.laf.useScreenMenuBar=true"
fi

@WRAP_JAR@

# vim:ts=3
