#! /bin/sh

# Merge annotations from an old results file into
# a new results file.

@GET_FBHOME@

@SET_DEFAULT_JAVA@

fb_jvmargs=''
out='no'

while [ $# -gt 0 ] && [ "$out" = "no" ]; do
	case $1 in
	-vi)
		fb_jvmargs="-DmergeResults.vi=true $fb_jvmargs"
		shift
		;;

	-update)
		fb_jvmargs="-DmergeResults.update=true $fb_jvmargs"
		shift
		;;

	*)
		out="yes"
		;;
	esac
done

fb_jvmargs="$fb_jvmargs"
fb_mainclass=edu.umd.cs.findbugs.MergeResults

@WRAP_JAVA@

# vim:ts=3
