#! /bin/sh

# Update an existing bug collection to include new analysis results.
# Old results are preserved.  The idea is that you can use this
# script to continuously maintain a findbugs history for your project.

@GET_FBHOME@

@SET_DEFAULT_JAVA@

fb_mainclass=edu.umd.cs.findbugs.UpdateBugCollection

@WRAP_JAVA@
