/*
 * FindBugs - Find Bugs in Java programs
 * Copyright (C) 2008 David H. Hovemeyer <david.hovemeyer@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package edu.umd.cs.findbugs.gui2;

import java.awt.CardLayout;

/**
 * Wizard dialog to automatically find and configure
 * source directories for a project.
 * 
 * @author David Hovemeyer
 */
public class SourceDirectoryWizard extends javax.swing.JDialog {
    
    private static final int MIN_STEP = 1;
    private static final int MAX_STEP = 2;
    
    /** Creates new form SourceDirectoryWizard */
    public SourceDirectoryWizard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setStep(1);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                contentPanel = new javax.swing.JPanel();
                firstPanel = new javax.swing.JPanel();
                sourceRootLabel = new javax.swing.JLabel();
                sourceRootBox = new javax.swing.JTextField();
                srcFileIconLabel = new javax.swing.JLabel();
                card1TitleLabel = new javax.swing.JLabel();
                browseButton = new javax.swing.JButton();
                card1Explanation1Label = new javax.swing.JLabel();
                card1Explanation2Label = new javax.swing.JLabel();
                card1Explanation3Label = new javax.swing.JLabel();
                secondPanel = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                previousButton = new javax.swing.JButton();
                nextButton = new javax.swing.JButton();
                finshButton = new javax.swing.JButton();
                errorMessageLabel = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("FindBugs Source Directory Configuration Wizard");

                contentPanel.setLayout(new java.awt.CardLayout());

                firstPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

                sourceRootLabel.setText("Top-level source directory:");

                srcFileIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/umd/cs/findbugs/gui2/source_java.png"))); // NOI18N

                card1TitleLabel.setFont(new java.awt.Font("Dialog", 1, 24));
                card1TitleLabel.setText("Where are your source files?");

                browseButton.setText("Browse...");

                card1Explanation1Label.setFont(new java.awt.Font("SansSerif", 0, 14));
                card1Explanation1Label.setText("Enter the top-level directory");

                card1Explanation2Label.setFont(new java.awt.Font("SansSerif", 0, 14));
                card1Explanation2Label.setText("containing your application's");

                card1Explanation3Label.setFont(new java.awt.Font("SansSerif", 0, 14));
                card1Explanation3Label.setText("source files.");

                javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
                firstPanel.setLayout(firstPanelLayout);
                firstPanelLayout.setHorizontalGroup(
                        firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(firstPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sourceRootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sourceRootBox, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(browseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                .addGap(25, 25, 25))
                                        .addGroup(firstPanelLayout.createSequentialGroup()
                                                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(card1TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(firstPanelLayout.createSequentialGroup()
                                                                .addComponent(srcFileIconLabel)
                                                                .addGap(87, 87, 87)
                                                                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(card1Explanation3Label)
                                                                        .addComponent(card1Explanation2Label)
                                                                        .addComponent(card1Explanation1Label))))
                                                .addContainerGap(229, Short.MAX_VALUE))))
                );
                firstPanelLayout.setVerticalGroup(
                        firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(card1TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(firstPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(srcFileIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(firstPanelLayout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(card1Explanation1Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(card1Explanation2Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(card1Explanation3Label)))
                                .addGap(27, 27, 27)
                                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(browseButton)
                                        .addComponent(sourceRootBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sourceRootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72))
                );

                contentPanel.add(firstPanel, "card1");

                jScrollPane1.setViewportView(jList1);

                jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14));
                jLabel1.setText("Source directories found:");

                jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14));
                jLabel2.setText("Click Finish to accept this");

                jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14));
                jLabel3.setText("list of source directories");

                javax.swing.GroupLayout secondPanelLayout = new javax.swing.GroupLayout(secondPanel);
                secondPanel.setLayout(secondPanelLayout);
                secondPanelLayout.setHorizontalGroup(
                        secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                secondPanelLayout.setVerticalGroup(
                        secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(secondPanelLayout.createSequentialGroup()
                                .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(secondPanelLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                                        .addGroup(secondPanelLayout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                .addContainerGap())
                );

                contentPanel.add(secondPanel, "card2");

                previousButton.setText("<< Previous");
                previousButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                previousButtonActionPerformed(evt);
                        }
                });

                nextButton.setText("Next >>");
                nextButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nextButtonActionPerformed(evt);
                        }
                });

                finshButton.setText("Finish");
                finshButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                finshButtonActionPerformed(evt);
                        }
                });

                errorMessageLabel.setFont(new java.awt.Font("SansSerif", 1, 14));
                errorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(248, Short.MAX_VALUE)
                                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(finshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(76, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(previousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(finshButton))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
    if (step > MIN_STEP) {
        setStep(step - 1);
    }
}//GEN-LAST:event_previousButtonActionPerformed

private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
    if (step < MAX_STEP) {
        setStep(step + 1);
    }
}//GEN-LAST:event_nextButtonActionPerformed

private void finshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finshButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_finshButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SourceDirectoryWizard dialog = new SourceDirectoryWizard(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton browseButton;
        private javax.swing.JLabel card1Explanation1Label;
        private javax.swing.JLabel card1Explanation2Label;
        private javax.swing.JLabel card1Explanation3Label;
        private javax.swing.JLabel card1TitleLabel;
        private javax.swing.JPanel contentPanel;
        private javax.swing.JLabel errorMessageLabel;
        private javax.swing.JButton finshButton;
        private javax.swing.JPanel firstPanel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JList jList1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton nextButton;
        private javax.swing.JButton previousButton;
        private javax.swing.JPanel secondPanel;
        private javax.swing.JTextField sourceRootBox;
        private javax.swing.JLabel sourceRootLabel;
        private javax.swing.JLabel srcFileIconLabel;
        // End of variables declaration//GEN-END:variables

    private int step;

    private void setStep(int step) {
        if (step < MIN_STEP || step > MAX_STEP) {
            throw new IllegalArgumentException("Invalid step " + step);
        }
        this.step = step;
        previousButton.setEnabled(step != MIN_STEP);
        nextButton.setEnabled(step != MAX_STEP);
        
        CardLayout cards = (CardLayout) contentPanel.getLayout();
        cards.show(contentPanel, "card" + step);
    }
}
