// Generated by the protocol buffer compiler.  DO NOT EDIT!

package edu.umd.cs.findbugs.cloud.appEngine.protobuf;

public final class ProtoClasses {
  private ProtoClasses() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class HashList extends
      com.google.protobuf.GeneratedMessage {
    // Use HashList.newBuilder() to construct.
    private HashList() {}
    
    private static final HashList defaultInstance = new HashList();
    public static HashList getDefaultInstance() {
      return defaultInstance;
    }
    
    public HashList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_HashList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_HashList_fieldAccessorTable;
    }
    
    // repeated string hashes = 1;
    public static final int HASHES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.String> hashes_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getHashesList() {
      return hashes_;
    }
    public int getHashesCount() { return hashes_.size(); }
    public java.lang.String getHashes(int index) {
      return hashes_.get(index);
    }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.lang.String element : getHashesList()) {
        output.writeString(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (java.lang.String element : getHashesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getHashesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList result;
      
      // Construct using edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList();
        return builder;
      }
      
      protected edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList.getDescriptor();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList getDefaultInstanceForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.hashes_ != java.util.Collections.EMPTY_LIST) {
          result.hashes_ =
            java.util.Collections.unmodifiableList(result.hashes_);
        }
        edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList) {
          return mergeFrom((edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList other) {
        if (other == edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList.getDefaultInstance()) return this;
        if (!other.hashes_.isEmpty()) {
          if (result.hashes_.isEmpty()) {
            result.hashes_ = new java.util.ArrayList<java.lang.String>();
          }
          result.hashes_.addAll(other.hashes_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              addHashes(input.readString());
              break;
            }
          }
        }
      }
      
      
      // repeated string hashes = 1;
      public java.util.List<java.lang.String> getHashesList() {
        return java.util.Collections.unmodifiableList(result.hashes_);
      }
      public int getHashesCount() {
        return result.getHashesCount();
      }
      public java.lang.String getHashes(int index) {
        return result.getHashes(index);
      }
      public Builder setHashes(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hashes_.set(index, value);
        return this;
      }
      public Builder addHashes(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.hashes_.isEmpty()) {
          result.hashes_ = new java.util.ArrayList<java.lang.String>();
        }
        result.hashes_.add(value);
        return this;
      }
      public Builder addAllHashes(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.hashes_.isEmpty()) {
          result.hashes_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.hashes_);
        return this;
      }
      public Builder clearHashes() {
        result.hashes_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.getDescriptor();
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internalForceInit();
    }
  }
  
  public static final class IssueList extends
      com.google.protobuf.GeneratedMessage {
    // Use IssueList.newBuilder() to construct.
    private IssueList() {}
    
    private static final IssueList defaultInstance = new IssueList();
    public static IssueList getDefaultInstance() {
      return defaultInstance;
    }
    
    public IssueList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_IssueList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_IssueList_fieldAccessorTable;
    }
    
    // repeated string missingIssues = 1;
    public static final int MISSINGISSUES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.String> missingIssues_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getMissingIssuesList() {
      return missingIssues_;
    }
    public int getMissingIssuesCount() { return missingIssues_.size(); }
    public java.lang.String getMissingIssues(int index) {
      return missingIssues_.get(index);
    }
    
    // repeated .edu.umd.cs.findbugs.cloud.appEngine.protobuf.Issue foundIssues = 2;
    public static final int FOUNDISSUES_FIELD_NUMBER = 2;
    private java.util.List<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue> foundIssues_ =
      java.util.Collections.emptyList();
    public java.util.List<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue> getFoundIssuesList() {
      return foundIssues_;
    }
    public int getFoundIssuesCount() { return foundIssues_.size(); }
    public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue getFoundIssues(int index) {
      return foundIssues_.get(index);
    }
    
    public final boolean isInitialized() {
      for (edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue element : getFoundIssuesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.lang.String element : getMissingIssuesList()) {
        output.writeString(1, element);
      }
      for (edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue element : getFoundIssuesList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (java.lang.String element : getMissingIssuesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getMissingIssuesList().size();
      }
      for (edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue element : getFoundIssuesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList result;
      
      // Construct using edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList();
        return builder;
      }
      
      protected edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList.getDescriptor();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList getDefaultInstanceForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.missingIssues_ != java.util.Collections.EMPTY_LIST) {
          result.missingIssues_ =
            java.util.Collections.unmodifiableList(result.missingIssues_);
        }
        if (result.foundIssues_ != java.util.Collections.EMPTY_LIST) {
          result.foundIssues_ =
            java.util.Collections.unmodifiableList(result.foundIssues_);
        }
        edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList) {
          return mergeFrom((edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList other) {
        if (other == edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList.getDefaultInstance()) return this;
        if (!other.missingIssues_.isEmpty()) {
          if (result.missingIssues_.isEmpty()) {
            result.missingIssues_ = new java.util.ArrayList<java.lang.String>();
          }
          result.missingIssues_.addAll(other.missingIssues_);
        }
        if (!other.foundIssues_.isEmpty()) {
          if (result.foundIssues_.isEmpty()) {
            result.foundIssues_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue>();
          }
          result.foundIssues_.addAll(other.foundIssues_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              addMissingIssues(input.readString());
              break;
            }
            case 18: {
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.Builder subBuilder = edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFoundIssues(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated string missingIssues = 1;
      public java.util.List<java.lang.String> getMissingIssuesList() {
        return java.util.Collections.unmodifiableList(result.missingIssues_);
      }
      public int getMissingIssuesCount() {
        return result.getMissingIssuesCount();
      }
      public java.lang.String getMissingIssues(int index) {
        return result.getMissingIssues(index);
      }
      public Builder setMissingIssues(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.missingIssues_.set(index, value);
        return this;
      }
      public Builder addMissingIssues(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.missingIssues_.isEmpty()) {
          result.missingIssues_ = new java.util.ArrayList<java.lang.String>();
        }
        result.missingIssues_.add(value);
        return this;
      }
      public Builder addAllMissingIssues(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.missingIssues_.isEmpty()) {
          result.missingIssues_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.missingIssues_);
        return this;
      }
      public Builder clearMissingIssues() {
        result.missingIssues_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .edu.umd.cs.findbugs.cloud.appEngine.protobuf.Issue foundIssues = 2;
      public java.util.List<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue> getFoundIssuesList() {
        return java.util.Collections.unmodifiableList(result.foundIssues_);
      }
      public int getFoundIssuesCount() {
        return result.getFoundIssuesCount();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue getFoundIssues(int index) {
        return result.getFoundIssues(index);
      }
      public Builder setFoundIssues(int index, edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.foundIssues_.set(index, value);
        return this;
      }
      public Builder setFoundIssues(int index, edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.Builder builderForValue) {
        result.foundIssues_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFoundIssues(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.foundIssues_.isEmpty()) {
          result.foundIssues_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue>();
        }
        result.foundIssues_.add(value);
        return this;
      }
      public Builder addFoundIssues(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.Builder builderForValue) {
        if (result.foundIssues_.isEmpty()) {
          result.foundIssues_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue>();
        }
        result.foundIssues_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFoundIssues(
          java.lang.Iterable<? extends edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue> values) {
        if (result.foundIssues_.isEmpty()) {
          result.foundIssues_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue>();
        }
        super.addAll(values, result.foundIssues_);
        return this;
      }
      public Builder clearFoundIssues() {
        result.foundIssues_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.getDescriptor();
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internalForceInit();
    }
  }
  
  public static final class Issue extends
      com.google.protobuf.GeneratedMessage {
    // Use Issue.newBuilder() to construct.
    private Issue() {}
    
    private static final Issue defaultInstance = new Issue();
    public static Issue getDefaultInstance() {
      return defaultInstance;
    }
    
    public Issue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Issue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Issue_fieldAccessorTable;
    }
    
    // required string hash = 1;
    public static final int HASH_FIELD_NUMBER = 1;
    private boolean hasHash;
    private java.lang.String hash_ = "";
    public boolean hasHash() { return hasHash; }
    public java.lang.String getHash() { return hash_; }
    
    // required string bugPattern = 2;
    public static final int BUGPATTERN_FIELD_NUMBER = 2;
    private boolean hasBugPattern;
    private java.lang.String bugPattern_ = "";
    public boolean hasBugPattern() { return hasBugPattern; }
    public java.lang.String getBugPattern() { return bugPattern_; }
    
    // required int32 priority = 3;
    public static final int PRIORITY_FIELD_NUMBER = 3;
    private boolean hasPriority;
    private int priority_ = 0;
    public boolean hasPriority() { return hasPriority; }
    public int getPriority() { return priority_; }
    
    // required int32 rank = 8;
    public static final int RANK_FIELD_NUMBER = 8;
    private boolean hasRank;
    private int rank_ = 0;
    public boolean hasRank() { return hasRank; }
    public int getRank() { return rank_; }
    
    // required string primaryClass = 4;
    public static final int PRIMARYCLASS_FIELD_NUMBER = 4;
    private boolean hasPrimaryClass;
    private java.lang.String primaryClass_ = "";
    public boolean hasPrimaryClass() { return hasPrimaryClass; }
    public java.lang.String getPrimaryClass() { return primaryClass_; }
    
    // optional int64 firstSeen = 5;
    public static final int FIRSTSEEN_FIELD_NUMBER = 5;
    private boolean hasFirstSeen;
    private long firstSeen_ = 0L;
    public boolean hasFirstSeen() { return hasFirstSeen; }
    public long getFirstSeen() { return firstSeen_; }
    
    // optional int64 lastSeen = 6;
    public static final int LASTSEEN_FIELD_NUMBER = 6;
    private boolean hasLastSeen;
    private long lastSeen_ = 0L;
    public boolean hasLastSeen() { return hasLastSeen; }
    public long getLastSeen() { return lastSeen_; }
    
    // repeated .edu.umd.cs.findbugs.cloud.appEngine.protobuf.Evaluation evaluations = 7;
    public static final int EVALUATIONS_FIELD_NUMBER = 7;
    private java.util.List<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation> evaluations_ =
      java.util.Collections.emptyList();
    public java.util.List<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation> getEvaluationsList() {
      return evaluations_;
    }
    public int getEvaluationsCount() { return evaluations_.size(); }
    public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation getEvaluations(int index) {
      return evaluations_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasHash) return false;
      if (!hasBugPattern) return false;
      if (!hasPriority) return false;
      if (!hasRank) return false;
      if (!hasPrimaryClass) return false;
      for (edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation element : getEvaluationsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasHash()) {
        output.writeString(1, getHash());
      }
      if (hasBugPattern()) {
        output.writeString(2, getBugPattern());
      }
      if (hasPriority()) {
        output.writeInt32(3, getPriority());
      }
      if (hasPrimaryClass()) {
        output.writeString(4, getPrimaryClass());
      }
      if (hasFirstSeen()) {
        output.writeInt64(5, getFirstSeen());
      }
      if (hasLastSeen()) {
        output.writeInt64(6, getLastSeen());
      }
      for (edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation element : getEvaluationsList()) {
        output.writeMessage(7, element);
      }
      if (hasRank()) {
        output.writeInt32(8, getRank());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasHash()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getHash());
      }
      if (hasBugPattern()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getBugPattern());
      }
      if (hasPriority()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getPriority());
      }
      if (hasPrimaryClass()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getPrimaryClass());
      }
      if (hasFirstSeen()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getFirstSeen());
      }
      if (hasLastSeen()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, getLastSeen());
      }
      for (edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation element : getEvaluationsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, element);
      }
      if (hasRank()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, getRank());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue result;
      
      // Construct using edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue();
        return builder;
      }
      
      protected edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.getDescriptor();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue getDefaultInstanceForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.evaluations_ != java.util.Collections.EMPTY_LIST) {
          result.evaluations_ =
            java.util.Collections.unmodifiableList(result.evaluations_);
        }
        edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue) {
          return mergeFrom((edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue other) {
        if (other == edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.getDefaultInstance()) return this;
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasBugPattern()) {
          setBugPattern(other.getBugPattern());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (other.hasPrimaryClass()) {
          setPrimaryClass(other.getPrimaryClass());
        }
        if (other.hasFirstSeen()) {
          setFirstSeen(other.getFirstSeen());
        }
        if (other.hasLastSeen()) {
          setLastSeen(other.getLastSeen());
        }
        if (!other.evaluations_.isEmpty()) {
          if (result.evaluations_.isEmpty()) {
            result.evaluations_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation>();
          }
          result.evaluations_.addAll(other.evaluations_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setHash(input.readString());
              break;
            }
            case 18: {
              setBugPattern(input.readString());
              break;
            }
            case 24: {
              setPriority(input.readInt32());
              break;
            }
            case 34: {
              setPrimaryClass(input.readString());
              break;
            }
            case 40: {
              setFirstSeen(input.readInt64());
              break;
            }
            case 48: {
              setLastSeen(input.readInt64());
              break;
            }
            case 58: {
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.Builder subBuilder = edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEvaluations(subBuilder.buildPartial());
              break;
            }
            case 64: {
              setRank(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string hash = 1;
      public boolean hasHash() {
        return result.hasHash();
      }
      public java.lang.String getHash() {
        return result.getHash();
      }
      public Builder setHash(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHash = true;
        result.hash_ = value;
        return this;
      }
      public Builder clearHash() {
        result.hasHash = false;
        result.hash_ = getDefaultInstance().getHash();
        return this;
      }
      
      // required string bugPattern = 2;
      public boolean hasBugPattern() {
        return result.hasBugPattern();
      }
      public java.lang.String getBugPattern() {
        return result.getBugPattern();
      }
      public Builder setBugPattern(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBugPattern = true;
        result.bugPattern_ = value;
        return this;
      }
      public Builder clearBugPattern() {
        result.hasBugPattern = false;
        result.bugPattern_ = getDefaultInstance().getBugPattern();
        return this;
      }
      
      // required int32 priority = 3;
      public boolean hasPriority() {
        return result.hasPriority();
      }
      public int getPriority() {
        return result.getPriority();
      }
      public Builder setPriority(int value) {
        result.hasPriority = true;
        result.priority_ = value;
        return this;
      }
      public Builder clearPriority() {
        result.hasPriority = false;
        result.priority_ = 0;
        return this;
      }
      
      // required int32 rank = 8;
      public boolean hasRank() {
        return result.hasRank();
      }
      public int getRank() {
        return result.getRank();
      }
      public Builder setRank(int value) {
        result.hasRank = true;
        result.rank_ = value;
        return this;
      }
      public Builder clearRank() {
        result.hasRank = false;
        result.rank_ = 0;
        return this;
      }
      
      // required string primaryClass = 4;
      public boolean hasPrimaryClass() {
        return result.hasPrimaryClass();
      }
      public java.lang.String getPrimaryClass() {
        return result.getPrimaryClass();
      }
      public Builder setPrimaryClass(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPrimaryClass = true;
        result.primaryClass_ = value;
        return this;
      }
      public Builder clearPrimaryClass() {
        result.hasPrimaryClass = false;
        result.primaryClass_ = getDefaultInstance().getPrimaryClass();
        return this;
      }
      
      // optional int64 firstSeen = 5;
      public boolean hasFirstSeen() {
        return result.hasFirstSeen();
      }
      public long getFirstSeen() {
        return result.getFirstSeen();
      }
      public Builder setFirstSeen(long value) {
        result.hasFirstSeen = true;
        result.firstSeen_ = value;
        return this;
      }
      public Builder clearFirstSeen() {
        result.hasFirstSeen = false;
        result.firstSeen_ = 0L;
        return this;
      }
      
      // optional int64 lastSeen = 6;
      public boolean hasLastSeen() {
        return result.hasLastSeen();
      }
      public long getLastSeen() {
        return result.getLastSeen();
      }
      public Builder setLastSeen(long value) {
        result.hasLastSeen = true;
        result.lastSeen_ = value;
        return this;
      }
      public Builder clearLastSeen() {
        result.hasLastSeen = false;
        result.lastSeen_ = 0L;
        return this;
      }
      
      // repeated .edu.umd.cs.findbugs.cloud.appEngine.protobuf.Evaluation evaluations = 7;
      public java.util.List<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation> getEvaluationsList() {
        return java.util.Collections.unmodifiableList(result.evaluations_);
      }
      public int getEvaluationsCount() {
        return result.getEvaluationsCount();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation getEvaluations(int index) {
        return result.getEvaluations(index);
      }
      public Builder setEvaluations(int index, edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.evaluations_.set(index, value);
        return this;
      }
      public Builder setEvaluations(int index, edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.Builder builderForValue) {
        result.evaluations_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEvaluations(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.evaluations_.isEmpty()) {
          result.evaluations_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation>();
        }
        result.evaluations_.add(value);
        return this;
      }
      public Builder addEvaluations(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.Builder builderForValue) {
        if (result.evaluations_.isEmpty()) {
          result.evaluations_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation>();
        }
        result.evaluations_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEvaluations(
          java.lang.Iterable<? extends edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation> values) {
        if (result.evaluations_.isEmpty()) {
          result.evaluations_ = new java.util.ArrayList<edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation>();
        }
        super.addAll(values, result.evaluations_);
        return this;
      }
      public Builder clearEvaluations() {
        result.evaluations_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.getDescriptor();
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internalForceInit();
    }
  }
  
  public static final class Evaluation extends
      com.google.protobuf.GeneratedMessage {
    // Use Evaluation.newBuilder() to construct.
    private Evaluation() {}
    
    private static final Evaluation defaultInstance = new Evaluation();
    public static Evaluation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Evaluation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Evaluation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Evaluation_fieldAccessorTable;
    }
    
    // required string who = 1;
    public static final int WHO_FIELD_NUMBER = 1;
    private boolean hasWho;
    private java.lang.String who_ = "";
    public boolean hasWho() { return hasWho; }
    public java.lang.String getWho() { return who_; }
    
    // required string designation = 2;
    public static final int DESIGNATION_FIELD_NUMBER = 2;
    private boolean hasDesignation;
    private java.lang.String designation_ = "";
    public boolean hasDesignation() { return hasDesignation; }
    public java.lang.String getDesignation() { return designation_; }
    
    // required string comment = 3;
    public static final int COMMENT_FIELD_NUMBER = 3;
    private boolean hasComment;
    private java.lang.String comment_ = "";
    public boolean hasComment() { return hasComment; }
    public java.lang.String getComment() { return comment_; }
    
    // required int64 when = 5;
    public static final int WHEN_FIELD_NUMBER = 5;
    private boolean hasWhen;
    private long when_ = 0L;
    public boolean hasWhen() { return hasWhen; }
    public long getWhen() { return when_; }
    
    // optional .edu.umd.cs.findbugs.cloud.appEngine.protobuf.Invocation invocation = 6;
    public static final int INVOCATION_FIELD_NUMBER = 6;
    private boolean hasInvocation;
    private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation invocation_ = edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.getDefaultInstance();
    public boolean hasInvocation() { return hasInvocation; }
    public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation getInvocation() { return invocation_; }
    
    public final boolean isInitialized() {
      if (!hasWho) return false;
      if (!hasDesignation) return false;
      if (!hasComment) return false;
      if (!hasWhen) return false;
      if (hasInvocation()) {
        if (!getInvocation().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasWho()) {
        output.writeString(1, getWho());
      }
      if (hasDesignation()) {
        output.writeString(2, getDesignation());
      }
      if (hasComment()) {
        output.writeString(3, getComment());
      }
      if (hasWhen()) {
        output.writeInt64(5, getWhen());
      }
      if (hasInvocation()) {
        output.writeMessage(6, getInvocation());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasWho()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getWho());
      }
      if (hasDesignation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDesignation());
      }
      if (hasComment()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getComment());
      }
      if (hasWhen()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getWhen());
      }
      if (hasInvocation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getInvocation());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation result;
      
      // Construct using edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation();
        return builder;
      }
      
      protected edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.getDescriptor();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation getDefaultInstanceForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation) {
          return mergeFrom((edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation other) {
        if (other == edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.getDefaultInstance()) return this;
        if (other.hasWho()) {
          setWho(other.getWho());
        }
        if (other.hasDesignation()) {
          setDesignation(other.getDesignation());
        }
        if (other.hasComment()) {
          setComment(other.getComment());
        }
        if (other.hasWhen()) {
          setWhen(other.getWhen());
        }
        if (other.hasInvocation()) {
          mergeInvocation(other.getInvocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setWho(input.readString());
              break;
            }
            case 18: {
              setDesignation(input.readString());
              break;
            }
            case 26: {
              setComment(input.readString());
              break;
            }
            case 40: {
              setWhen(input.readInt64());
              break;
            }
            case 50: {
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.Builder subBuilder = edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.newBuilder();
              if (hasInvocation()) {
                subBuilder.mergeFrom(getInvocation());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInvocation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string who = 1;
      public boolean hasWho() {
        return result.hasWho();
      }
      public java.lang.String getWho() {
        return result.getWho();
      }
      public Builder setWho(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasWho = true;
        result.who_ = value;
        return this;
      }
      public Builder clearWho() {
        result.hasWho = false;
        result.who_ = getDefaultInstance().getWho();
        return this;
      }
      
      // required string designation = 2;
      public boolean hasDesignation() {
        return result.hasDesignation();
      }
      public java.lang.String getDesignation() {
        return result.getDesignation();
      }
      public Builder setDesignation(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDesignation = true;
        result.designation_ = value;
        return this;
      }
      public Builder clearDesignation() {
        result.hasDesignation = false;
        result.designation_ = getDefaultInstance().getDesignation();
        return this;
      }
      
      // required string comment = 3;
      public boolean hasComment() {
        return result.hasComment();
      }
      public java.lang.String getComment() {
        return result.getComment();
      }
      public Builder setComment(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasComment = true;
        result.comment_ = value;
        return this;
      }
      public Builder clearComment() {
        result.hasComment = false;
        result.comment_ = getDefaultInstance().getComment();
        return this;
      }
      
      // required int64 when = 5;
      public boolean hasWhen() {
        return result.hasWhen();
      }
      public long getWhen() {
        return result.getWhen();
      }
      public Builder setWhen(long value) {
        result.hasWhen = true;
        result.when_ = value;
        return this;
      }
      public Builder clearWhen() {
        result.hasWhen = false;
        result.when_ = 0L;
        return this;
      }
      
      // optional .edu.umd.cs.findbugs.cloud.appEngine.protobuf.Invocation invocation = 6;
      public boolean hasInvocation() {
        return result.hasInvocation();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation getInvocation() {
        return result.getInvocation();
      }
      public Builder setInvocation(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasInvocation = true;
        result.invocation_ = value;
        return this;
      }
      public Builder setInvocation(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.Builder builderForValue) {
        result.hasInvocation = true;
        result.invocation_ = builderForValue.build();
        return this;
      }
      public Builder mergeInvocation(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation value) {
        if (result.hasInvocation() &&
            result.invocation_ != edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.getDefaultInstance()) {
          result.invocation_ =
            edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.newBuilder(result.invocation_).mergeFrom(value).buildPartial();
        } else {
          result.invocation_ = value;
        }
        result.hasInvocation = true;
        return this;
      }
      public Builder clearInvocation() {
        result.hasInvocation = false;
        result.invocation_ = edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.getDefaultInstance();
        return this;
      }
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.getDescriptor();
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internalForceInit();
    }
  }
  
  public static final class Invocation extends
      com.google.protobuf.GeneratedMessage {
    // Use Invocation.newBuilder() to construct.
    private Invocation() {}
    
    private static final Invocation defaultInstance = new Invocation();
    public static Invocation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Invocation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Invocation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Invocation_fieldAccessorTable;
    }
    
    // required string who = 1;
    public static final int WHO_FIELD_NUMBER = 1;
    private boolean hasWho;
    private java.lang.String who_ = "";
    public boolean hasWho() { return hasWho; }
    public java.lang.String getWho() { return who_; }
    
    // required int64 startTime = 2;
    public static final int STARTTIME_FIELD_NUMBER = 2;
    private boolean hasStartTime;
    private long startTime_ = 0L;
    public boolean hasStartTime() { return hasStartTime; }
    public long getStartTime() { return startTime_; }
    
    // required int64 endTime = 3;
    public static final int ENDTIME_FIELD_NUMBER = 3;
    private boolean hasEndTime;
    private long endTime_ = 0L;
    public boolean hasEndTime() { return hasEndTime; }
    public long getEndTime() { return endTime_; }
    
    public final boolean isInitialized() {
      if (!hasWho) return false;
      if (!hasStartTime) return false;
      if (!hasEndTime) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasWho()) {
        output.writeString(1, getWho());
      }
      if (hasStartTime()) {
        output.writeInt64(2, getStartTime());
      }
      if (hasEndTime()) {
        output.writeInt64(3, getEndTime());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasWho()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getWho());
      }
      if (hasStartTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getStartTime());
      }
      if (hasEndTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getEndTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation result;
      
      // Construct using edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation();
        return builder;
      }
      
      protected edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.getDescriptor();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation getDefaultInstanceForType() {
        return edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation) {
          return mergeFrom((edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation other) {
        if (other == edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.getDefaultInstance()) return this;
        if (other.hasWho()) {
          setWho(other.getWho());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setWho(input.readString());
              break;
            }
            case 16: {
              setStartTime(input.readInt64());
              break;
            }
            case 24: {
              setEndTime(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required string who = 1;
      public boolean hasWho() {
        return result.hasWho();
      }
      public java.lang.String getWho() {
        return result.getWho();
      }
      public Builder setWho(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasWho = true;
        result.who_ = value;
        return this;
      }
      public Builder clearWho() {
        result.hasWho = false;
        result.who_ = getDefaultInstance().getWho();
        return this;
      }
      
      // required int64 startTime = 2;
      public boolean hasStartTime() {
        return result.hasStartTime();
      }
      public long getStartTime() {
        return result.getStartTime();
      }
      public Builder setStartTime(long value) {
        result.hasStartTime = true;
        result.startTime_ = value;
        return this;
      }
      public Builder clearStartTime() {
        result.hasStartTime = false;
        result.startTime_ = 0L;
        return this;
      }
      
      // required int64 endTime = 3;
      public boolean hasEndTime() {
        return result.hasEndTime();
      }
      public long getEndTime() {
        return result.getEndTime();
      }
      public Builder setEndTime(long value) {
        result.hasEndTime = true;
        result.endTime_ = value;
        return this;
      }
      public Builder clearEndTime() {
        result.hasEndTime = false;
        result.endTime_ = 0L;
        return this;
      }
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.getDescriptor();
    }
    
    static {
      edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_HashList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_HashList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_IssueList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_IssueList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Issue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Issue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Evaluation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Evaluation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Invocation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Invocation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoClasses.proto\022,edu.umd.cs.findbug" +
      "s.cloud.appEngine.protobuf\"\032\n\010HashList\022\016" +
      "\n\006hashes\030\001 \003(\t\"l\n\tIssueList\022\025\n\rmissingIs" +
      "sues\030\001 \003(\t\022H\n\013foundIssues\030\002 \003(\01323.edu.um" +
      "d.cs.findbugs.cloud.appEngine.protobuf.I" +
      "ssue\"\323\001\n\005Issue\022\014\n\004hash\030\001 \002(\t\022\022\n\nbugPatte" +
      "rn\030\002 \002(\t\022\020\n\010priority\030\003 \002(\005\022\014\n\004rank\030\010 \002(\005" +
      "\022\024\n\014primaryClass\030\004 \002(\t\022\021\n\tfirstSeen\030\005 \001(" +
      "\003\022\020\n\010lastSeen\030\006 \001(\003\022M\n\013evaluations\030\007 \003(\013" +
      "28.edu.umd.cs.findbugs.cloud.appEngine.p",
      "rotobuf.Evaluation\"\233\001\n\nEvaluation\022\013\n\003who" +
      "\030\001 \002(\t\022\023\n\013designation\030\002 \002(\t\022\017\n\007comment\030\003" +
      " \002(\t\022\014\n\004when\030\005 \002(\003\022L\n\ninvocation\030\006 \001(\01328" +
      ".edu.umd.cs.findbugs.cloud.appEngine.pro" +
      "tobuf.Invocation\"=\n\nInvocation\022\013\n\003who\030\001 " +
      "\002(\t\022\021\n\tstartTime\030\002 \002(\003\022\017\n\007endTime\030\003 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_HashList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_HashList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_HashList_descriptor,
              new java.lang.String[] { "Hashes", },
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList.class,
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.HashList.Builder.class);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_IssueList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_IssueList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_IssueList_descriptor,
              new java.lang.String[] { "MissingIssues", "FoundIssues", },
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList.class,
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.IssueList.Builder.class);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Issue_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Issue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Issue_descriptor,
              new java.lang.String[] { "Hash", "BugPattern", "Priority", "Rank", "PrimaryClass", "FirstSeen", "LastSeen", "Evaluations", },
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.class,
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Issue.Builder.class);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Evaluation_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Evaluation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Evaluation_descriptor,
              new java.lang.String[] { "Who", "Designation", "Comment", "When", "Invocation", },
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.class,
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Evaluation.Builder.class);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Invocation_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Invocation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umd_cs_findbugs_cloud_appEngine_protobuf_Invocation_descriptor,
              new java.lang.String[] { "Who", "StartTime", "EndTime", },
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.class,
              edu.umd.cs.findbugs.cloud.appEngine.protobuf.ProtoClasses.Invocation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
