#! /bin/sh

# Deprecated

# Create the union of two results files, preserving
# annotations in both files in the result.

@GET_FBHOME@

@SET_DEFAULT_JAVA@

fb_mainclass=edu.umd.cs.findbugs.workflow.UnionResults

@WRAP_JAVA@

# vim:ts=3
