name: Build
on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17.0.1+12, 17, 21, 25]
      max-parallel: 6
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    continue-on-error: true

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      # Disable gpg decryption of certificate for time being until we get new keys established
      #- name: Pre-build setup
      #  if: github.repository_owner == 'spotbugs'
      #  run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_SECRET_PASSPHRASE" --output spotbugs.jks .github/workflows/spotbugs.jks.gpg;
      #  env:
      #    GPG_SECRET_PASSPHRASE: ${{ secrets.GPG_SECRET_PASSPHRASE }}
      - name: Build with Sonar JDK ${{ matrix.java }}, ${{ matrix.os }}
        # https://community.sonarsource.com/t/sonarcloud-now-not-updating-github-pr-and-checks/6595/17
        if: matrix.java == '21'
        run: ./gradlew spotlessCheck build smoketest ${SONAR_LOGIN:+sonar} --no-daemon "-Dsonar.token=$SONAR_LOGIN" --scan
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          ORG_GRADLE_PROJECT_keystorepass: ${{ secrets.KEYSTORE_PASS }}
      - name: Build JDK ${{ matrix.java }}, ${{ matrix.os }}
        # https://community.sonarsource.com/t/sonarcloud-now-not-updating-github-pr-and-checks/6595/17
        if: matrix.java != '21'
        run: ./gradlew spotlessCheck build smoketest --no-daemon --scan
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          ORG_GRADLE_PROJECT_keystorepass: ${{ secrets.KEYSTORE_PASS }}
